config/routes.rb
Rails.application.routes.draw do
  resources :visites, only: :index
  resources :categories
  resources :annonces
  resources :organisations do
    get 'login', on: :member, action: :login_in
    get 'login', on: :collection, action: :login_form
    post 'login', on: :collection
  end
  root to: 'organisations#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_secure_password
  has_secure_password :read_password
  validates :nom, presence: true, length: { minimum: 3 }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 3 }, on: :create
  validates :read_password, presence: true, length: { minimum: 3 }, on: :create

  has_many :annonces, dependent: :destroy
  has_one :annonce, -> { order('created_at asc').limit(1) }, dependent: :destroy
  has_and_belongs_to_many :categories

  after_update :update_annonce

  private
  def update_annonce
    self.annonce&.update_attribute(:nom, self.nom)
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :set_organisation, only: [:show, :edit, :update, :destroy]
  before_action :check_admin_organisation, only: [:edit, :update, :destroy]

  # GET /organisations
  # GET /organisations.json
  def index
    @organisations = Organisation.includes(:annonces).all
  end

  # GET /organisations/1
  # GET /organisations/1.json
  def show
  end

  # GET /organisations/new
  def new
    @organisation = Organisation.new
  end

  # GET /organisations/1/edit
  def edit
  end

  # GET /organisations/login
  def login_form
    @organisations = Organisation.all
  end

  # GET /organisations/1/login
  def login_in
    @organisations = [Organisation.find(params[:id])]
    render :login_form
  end

  # POST /organisations/login
  def login
    reset_session
    @organisation = Organisation.find(params[:organisation][:id])
    if @organisation.authenticate(params[:organisation][:password])
      session[:organisation_id] = @organisation.id
      session[:admin] = true
      redirect_to Annonce, notice: "Authentifié avec succès en tant qu'admin !"
    elsif @organisation.authenticate_read_password(params[:organisation][:password])
      session[:organisation_id] = @organisation.id
      session[:admin] = false
      redirect_to Annonce, notice: 'Authentifié avec succès !'
    else 
      @organisations = [@organisation]
      flash.now[:alert] = "Mot de passe incorrect"
      render :login_form
    end
  end

  # POST /organisations
  # POST /organisations.json
  def create
    @organisation = Organisation.new(organisation_params)

    respond_to do |format|
      if @organisation.save
        reset_session
        session[:organisation_id] = @organisation.id
        session[:admin] = true
        a = @organisation.build_annonce(nom: @organisation.nom, password: @organisation.password)
        a.save(validate: false)
        @organisation.annonces << a
        @organisation.annonce.categories << Categorie.find(1)
        @organisation.categories << Categorie.find(1) unless @organisation.categories.exists?(1)
        format.html { redirect_to edit_annonce_url(@organisation.annonce), notice: 'Organisation créée avec succès.' }
        format.json { render :show, status: :created, location: @organisation }
      else
        format.html { render :new }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organisations/1
  # PATCH/PUT /organisations/1.json
  def update
    respond_to do |format|
      if @organisation.update(organisation_params)
        format.html { redirect_to @organisation, notice: 'Organisation modifiée avec succès.' }
        format.json { render :show, status: :ok, location: @organisation }
      else
        format.html { render :edit }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisations/1
  # DELETE /organisations/1.json
  def destroy
    if @organisation.authenticate(params[:password])
      @organisation.destroy
      respond_to do |format|
        format.html { redirect_to organisations_url, notice: 'Organisation supprimée avec succès.' }
        format.json { head :no_content }
      end
    else
      redirect_to @organisation, alert: 'Organisation non supprimée, mot de passe incorrect.' 
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_organisation
    @organisation = Organisation.find(params[:id])
  end
  def check_admin_organisation
    unless check_admin(@organisation)
      redirect_to :root, alert: "Accès réservé."
    end
  end

  # Only allow a list of trusted parameters through.
  def organisation_params
    params.require(:organisation).permit(:nom, :password, :password_confirmation, :read_password, :read_password_confirmation, :categorie_ids => [])
  end
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/views/organisations/_form.html.erb
<%= simple_form_for(@organisation) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <% action_edit = (action_name =~ /edit|update/) %>
  <% edit_message = action_edit ? "<strong>Laissez ces champs vides pour ne pas modifier le mot de passe.</strong> " : "" %>
  <div class="form-inputs">
    <%= f.input :nom %>
    <%= f.input :password, label: "Mot de passe admin", hint: "#{edit_message}Ce mot de passe ne doit pas être rendu public. Il vous permettra d’accéder aux fonctions d'administration de l’organisation.".html_safe %>
    <%= f.input :password_confirmation, required: ! action_edit, label: "Confirmation du mot de passe administrateur" %>
    <%= f.input :read_password, label: "Mot de passe pour les utilisateurs", hint: "#{edit_message}Afin de protéger les données des personnes, notamment leurs coordonnées, merci de déterminer un mot de passe à diffuser auprès des utilisateur&middot;ice&middot;s. Ce mot de passe leur permettra d’accéder à l’intégralité des données de l'orgagnisation.".html_safe %>
    <%= f.input :read_password_confirmation, required: ! action_edit, label: "Confirmation du mot de passe utilisateurs" %>
    <%= f.association :categories, hint:"Voici les différents types de coup de main qu’il est possible de proposer. À vous de choisir ceux qui seront proposés pour la rédaction des annonces des utilisateur&middot;ices. Il y en a peut-être qui ne sont pas pertinents dans votre organisation. Shift permet de sélectionner une plage, Ctrl un par un.<br>Pour ajouter de nouvelles catégories, il faudra aller dans le menu Catégories, accessible en haut.".html_safe, input_html: {size: Categorie.count} %> 
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Enregistrer les modifications", class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/organisations/edit.html.erb
<h1>Modifier Organisation</h1>

<%= render 'form', organisation: @organisation %>

<p class="mt-2">
<%= link_to 'Annuler', @organisation, class: "btn btn-secondary" %> 
<%= link_to 'Gérer le profil', edit_annonce_path(@organisation.annonce), class: "btn btn-outline-secondary", 'data-toggle': "tooltip", title: "Cela annulera aussi les changements en cours" %> 
<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#supprModal">
  Supprimer l'organisation
</button>
</p>

<!-- Modal -->
<div class="modal fade" id="supprModal" tabindex="-1" role="dialog" aria-labelledby="supprModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="supprModalLabel">Supprimer l'organisation</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_tag organisation_path(id: @organisation.id), method: :delete, class: "simple_form" do %>
        <div class="modal-body">
          <p>Êtes vous sûr&middot;e de vouloir supprimer l'organisation <%= @organisation.nom %> et les annonces (<%= @organisation.annonces.count %>) qui s'y trouvent ?</p>
          <div class="form-inputs">
            <%= label_tag :password %>
            <%= password_field_tag 'password', '' %>
          </div>

          <div class="form-actions">
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
          <input class="btn btn-danger" value='Supprimer cette organisation' type='submit' id='submit-form'/>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/organisations/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Coup2Main</h1>
  <p class="lead">Bienvenue sur notre plate-forme de partage de coups de main.</p>
  <hr class="my-4">
  <p>Vous trouverez ci-dessous la liste des organisations qui proposent ce service.<br>
  Pensez au bouton Aide en haut quand vous êtes perdu&middot;e&middot;s.</p>
  <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#mapModal">Voir sur la carte</button>
</div>

<div class="row row-cols-1 row-cols-md-3">
  <% @organisations.each do |organisation| %>
    <div class="col mb-3">
      <div class="card">
        <div class="card-header"><h5><%= organisation.nom %></h5></div>
        <div class="card-body">
          <p class="card-text">
          <% if organisation.annonce&.latlong? %>
            <a hidden href="geo:<%= organisation.annonce.latlong %>" data-map="<%= organisation.annonce.latlong %>" data-text="<%= organisation.nom %>">geo:<%= organisation.annonce.latlong%></a>
          <% end %>
          <% if organisation.annonce&.web? %>
            <a href="<%= organisation.annonce.web %>" target="_blank">Site web...</a>
          <% end %>
          </p>
        </div>
        <div class="card-footer">
          <%= link_to 'Se connecter', login_organisation_path(organisation), class: "btn btn-outline-secondary" %>
          <% if organisation == current_organisation && current_admin %>
            <%= link_to 'Modifier', edit_organisation_path(organisation), class: "btn btn-secondary" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<p>
<%= link_to 'Ajouter une organisation', new_organisation_path, class: "btn btn-outline-secondary" %>
</p>

<!-- Map Modal -->
<div class="modal fade" id="mapModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalLabel">Localisation des organisations</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="map" style='height:500px;'>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/organisations/login_form.html.erb
<div class="jumbotron">
  <h1 class="display-4">Coup2Main</h1>
  <p class="lead">Bienvenue sur notre plate-forme de partage de coups de main.</p>
  <hr class="my-4">
  <p>
  Pensez au bouton Aide en haut quand vous êtes perdu&middot;e&middot;s.
  <% if @organisations.count == 1 %>
    <br>
    Si vous ne retrouvez pas le mot de passe, demandez à <%= link_to @organisations.first.nom, @organisations.first %>.
  <% end %>
  </p>
</div>
<%= simple_form_for(:organisation, url: login_organisations_path) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <% plaintext = (@organisations.count == 1 ? "form-control-plaintext" : "") %>
    <%= f.input :id, collection: @organisations, label: "Organisation", :label_method => :nom, include_blank: false, include_hidden: false, input_html: {class: plaintext} %>
    <%= f.input :password, label: "Mot de passe d'accès" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Se connecter", class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/organisations/new.html.erb
<h1>Nouvelle Organisation</h1>

<p>
<% case request.host %>
<% when /127|192|localhost/ %>
  Version locale.
<% when /demo/ %>
  <strong>Version de test.</strong> Les données seront effacées régulièrement. <a href="https://coup2main.herokuapp.com/">Version complète</a>.
<% else %>
  Version de production. Si vous voulez tester l'application, vous pouvez utiliser la <a href="https://coup2main-demo.herokuapp.com/">version de test</a>.
<% end %>
</p>

<%= render 'form', organisation: @organisation %>
<p>Dans le prochain formulaire, vous devrez créer une annonce associée à votre structure, afin d'être joignable par les utilisateurs. Pensez à remplir la position, elle servira de position par défaut. Le mot de passe demandé est le mot de passe admin que vous venez de créer. N'oubliez pas vos mots de passes, il n'y a pas encore de moyens de les récupérer.</p>
<p><%= link_to 'Retour à la liste', organisations_path %></p>

app/views/organisations/show.html.erb
<% if current_organisation == @organisation %>
  <%= render @organisation.annonce %>
<% else %>
<div class="row row-cols-1 row-cols-md-3">
    <div class="col mb-3">
      <div class="card">
        <div class="card-header"><h5><%= @organisation.nom %></h5></div>
        <div class="card-body">
          <p class="card-text">
          <% if @organisation.annonce&.web? %>
            <a href="<%= @organisation.annonce.web %>" target="_blank">Site web...</a>
          <% end %>
          </p>
        </div>
        <div class="card-footer">
          <%= link_to 'Se connecter', login_organisation_path(@organisation), class: "btn btn-outline-secondary" %>
        </div>
      </div>
    </div>
</div>
<% end %>

<% if check_admin(@organisation) %>
  <p>
  <strong>Catégories autorisées dans l'organisation&nbsp;:</strong>
  </p>
  <ul>
    <% @organisation.categories.each do |cat| %>
      <li><%= cat.name %></li>
    <% end %>
  </ul>
  <p>
  <%= link_to 'Modifier les catégories ou les mots de passe', edit_organisation_path(@organisation), class: "btn btn-outline-secondary" %>
  <%= link_to 'Gérer le profil', edit_annonce_path(@organisation.annonce), class: "btn btn-outline-secondary" %> 
  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#supprModal">
    Supprimer l'organisation
  </button>
  </p>
<% end %>

<!-- Modal -->
<div class="modal fade" id="supprModal" tabindex="-1" role="dialog" aria-labelledby="supprModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="supprModalLabel">Supprimer l'organisation</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_tag organisation_path(id: @organisation.id), method: :delete, class: "simple_form" do %>
        <div class="modal-body">
          <div class="form-inputs">
            <%= label_tag :password %>
            <%= password_field_tag 'password', '' %>
          </div>
          <p>Êtes-vous sûr&middot;e de vouloir supprimer définitivement l'organisation <%= @organisation.nom %> et les <%= @organisation.annonces.count %> annonces qui y sont ?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
          <input class="btn btn-danger" value='Supprimer cette organisation' type='submit' id='submit-form'/>
        </div>
      <% end %>
    </div>
  </div>
</div>