config/routes.rb
Rails.application.routes.draw do
  resources :visites, only: :index
  resources :categories
  resources :annonces
  resources :organisations do
    get 'login', on: :member, action: :login_in
    get 'login', on: :collection, action: :login_form
    post 'login', on: :collection
  end
  root to: 'organisations#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/annonce.rb
class Annonce < ApplicationRecord
  has_secure_password
  validates :nom, presence: true, length: { minimum: 3 }, uniqueness: { case_sensitive: false, scope: :organisation }
  validates :password, presence: true, length: { minimum: 3 }, on: :create
  validates :mail, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }, if: :mail? 
  validates :tel1, format: { with: /\A((\+)33\s?|0)[1-9]\s?(\d{2}\s?){4}\z/ }, if: :tel1? # +33299876554 ou 06 17 62 17 71
  validates :tel2, format: { with: /\A((\+)33\s?|0)[1-9]\s?(\d{2}\s?){4}\z/ }, if: :tel2? # +33299876554 ou 06 17 62 17 71
  validates :distance, numericality: { only_integer: true, greater_than_or_equal_to: 1 }, presence: true, if: :latlong?
  validates :latlong, format: { with: /\A-?\d+(\.\d+)?,-?\d+(\.\d+)?\z/ }, if: :latlong? # -22.78,-43.77 
  validates :categories, presence: true
  validate :any_contact_present?
  validate :password_different_from_org

  def any_contact_present?
    if %w(mail tel1 tel2 web).all?{|attr| self[attr].blank?}
      errors.add :base, "Au moins un moyen de contact doit être rempli"
    end
  end
  def password_different_from_org
    if self.organisation.authenticate_read_password(password) || self.organisation.authenticate(password)
      errors.add :password, "ne doit pas être le même que pour l'accès aux annonces."
    end
  end

  belongs_to :organisation
  has_and_belongs_to_many :categories
  def web
    _web = read_attribute(:web).try(:downcase)
    if(_web.present?)
      unless _web[/\Ahttp:\/\//] || _web[/\Ahttps:\/\//]
        _web = "http://#{_web}"
      end
    end
    _web
  end
end

app/controllers/annonces_controller.rb
class AnnoncesController < ApplicationController
  before_action :check_organisation
  before_action :set_annonce, only: [:show, :edit, :update, :destroy]

  # GET /annonces
  # GET /annonces.json
  def index
    if params["filtre"] && ! params["filtre"]["categorie"].blank?
      id = params["filtre"]["categorie"].to_i
      if id >= 0
        @categorie = Categorie.find(id)
        @annonces = current_organisation.annonces.joins(:categories).includes(:categories).where(:annonces_categories => {categorie_id: id })
        if params["filtre"]["latlong"] && params["filtre"]["latlong"].length > 3
          session["latlong"] = params["filtre"]["latlong"]
          @annonces = @annonces.select do |annonce| 
            if annonce.latlong.present?
              helpers.distance(params["filtre"]["latlong"].split(',').map(&:to_f), annonce.latlong.split(',').map(&:to_f)) < annonce.distance 
            else
              false
            end
          end
        end
      else
        @categorie = Categorie.new(id: -1)
        @annonces = current_organisation.annonces.includes(:categories).where.not(autres: [nil, ""])
      end
    else
      @annonces = current_organisation.annonces.includes(:categories).all
    end
  end

  # GET /annonces/1
  # GET /annonces/1.json
  def show
  end

  # GET /annonces/new
  def new
    @annonce = Annonce.new
  end

  # GET /annonces/1/edit
  def edit
  end

  # POST /annonces
  # POST /annonces.json
  def create
    @annonce = current_organisation.annonces.new(annonce_params)

    respond_to do |format|
      if @annonce.save
        format.html { redirect_to @annonce, notice: 'Annonce créée avec succès.' }
        format.json { render :show, status: :created, location: @annonce }
      else
        format.html { render :new }
        format.json { render json: @annonce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /annonces/1
  # PATCH/PUT /annonces/1.json
  def update
    respond_to do |format|
      if params[:annonce][:old_password] && @annonce.authenticate(params[:annonce][:old_password])
        if @annonce.update(annonce_params)
          format.html { redirect_to @annonce, notice: 'Mot de passe modifié avec succès.' }
        else
          format.html { redirect_to @annonce, alert: 'Mot de passe non autorisé.' }
        end
      else
        @annonce.assign_attributes(annonce_params.except(:password))
        if @annonce.authenticate(params[:annonce][:password])
          if @annonce.save
            format.html { redirect_to @annonce, notice: 'Annonce modifiée avec succès.' }
            format.json { render :show, status: :ok, location: @annonce }
          else
            format.html { render :edit }
            format.json { render json: @annonce.errors, status: :unprocessable_entity }
          end
        else
          flash.now[:alert] = 'Modication refusée, mot de passe incorrect.'
          format.html { render :edit }
        end
      end
    end
  end

  # DELETE /annonces/1
  # DELETE /annonces/1.json
  def destroy
    if @annonce.authenticate(params[:password])
      @annonce.destroy
      respond_to do |format|
        format.html { redirect_to annonces_url, notice: 'Annonce supprimée avec succès.' }
        format.json { head :no_content }
      end
    else
      redirect_to @annonce, alert: 'Annonce non supprimée, mot de passe incorrect.' 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def check_organisation
      unless current_organisation
        redirect_to :root, alert: "Accès réservé."
      end
    end
    def set_annonce
      @annonce = current_organisation.annonces.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def annonce_params
      params.require(:annonce).permit(:nom, :latlong, :distance, :adresse, :autres, :password, :password_confirmation, :tel1, :tel2, :web, :mail, :categorie_ids => [])
    end
end

app/helpers/annonces_helper.rb
module AnnoncesHelper
end

app/views/annonces/_annonce.html.erb
<dl class="row mt-3">
  <dt class="col-sm-3">Nom&nbsp;:</dt>
  <dd class="col-sm-9"><%= annonce.nom %></dd>

  <% if annonce.tel1.present? %>
    <dt class="col-sm-3">Numéro de téléphone&nbsp;:</dt>
    <dd class="col-sm-9"><a href="tel:<%= annonce.tel1 %>"><%= annonce.tel1 %></a></dd>
  <% end %>

  <% if annonce.tel2.present? %>
    <dt class="col-sm-3">Autre numéro de téléphone&nbsp;:</dt>
    <dd class="col-sm-9"><a href="tel:<%= annonce.tel2 %>"><%= annonce.tel2 %></a></dd>
  <% end %>

  <% if annonce.mail.present? %>
    <dt class="col-sm-3">Adresse mail&nbsp;:</dt>
    <dd class="col-sm-9"><a href="mailto:<%= annonce.mail %>"><%= annonce.mail %></a></dd>
  <% end %>

  <% if annonce.web.present? %>
    <dt class="col-sm-3">Site web&nbsp;:</dt>
    <dd class="col-sm-9"><a href="<%= annonce.web %>" target="_blank"><%= annonce.web %></a></dd>
  <% end %>

  <% if annonce.adresse.present? %>
    <dt class="col-sm-3">Adresse&nbsp;:</dt>
    <dd class="col-sm-9"><%= annonce.adresse %></dd>
  <% end %>

  <% if annonce.distance.present? %>
    <dt class="col-sm-3">Distance maximale&nbsp;:</dt>
    <dd class="col-sm-9">
      <%= annonce.distance %>km
      <%= hidden_field :annonce, :distance %>
    </dd>
  <% end %>

  <% if annonce.latlong.present? %>
    <dt class="col-sm-3">Localisation&nbsp;:</dt>
    <dd class="col-sm-9">
      <button type="button" class="btn btn-outline-secondary" data-toggle="modal" data-target="#mapModal">Voir sur la carte.</button>
      <a href="geo:<%= annonce.latlong %>">geo:<%= annonce.latlong%></a>
    </dd>
  <% end %>

    <dt class="col-sm-3">Catégories&nbsp;:</dt>
  <ul class="col-sm-9">
    <% annonce.categories.each do |cat| %>
      <li><%= cat.name %></li>
    <% end %>
  </ul>

  <% if annonce.autres.present? %>
    <dt class="col-sm-3">Autres&nbsp;:</dt>
    <dd class="col-sm-9"><%= markdown(annonce.autres) %></dd>
  <% end %>
</dl>

<% if annonce.latlong.present? %>
  <!-- Map Modal -->
  <div class="modal fade" id="mapModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modalLabel">Localisation sur carte</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div id="map" style='height:500px;' data-map="<%= annonce.latlong %>">
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/annonces/_form.html.erb
<%= simple_form_for(@annonce, wrapper: :input_group ) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="form-row">
      <%= f.input :nom, wrapper_html: { class: 'col-md' } %>
      <%= f.input :password, required: true, label: "Mot de passe (pour modifier l'annonce)", wrapper_html: { class: 'col-md' , 'data-toggle': "tooltip", title: "Ce mot de passe doit être unique et connu de vous seul&middot;e".html_safe} %>
      <% if action_name =~ /new|create/ %>
        <%= f.input :password_confirmation, required: true, label: "Confirmation du mot de passe", wrapper_html: { class: 'col-md' } %>
      <% end %>
    </div>
    <small class="form-text text-muted">
      Seul un des moyens de contact ci-dessous est indispensable. À vous de choisir !
    </small>
    <div class="form-row">
      <%= f.input :tel1, label: "Téléphone", wrapper_html: { class: 'col-md-6' } %>
      <%= f.input :tel2, label: "Autre téléphone", wrapper_html: { class: 'col-md-6' } %>
    </div>
    <div class="form-row">
      <%= f.input :mail, wrapper_html: { class: 'col-md-6' } %>
      <%= f.input :web, wrapper_html: { class: 'col-md-6' } %>
    </div>
    <%= f.input :adresse %>
    <div class="form-row align-items-end">
      <%= f.input :distance, label: "Combien de kilomètres je suis prêt&middot;e à faire (à vol d'oiseau)&nbsp;:".html_safe, wrapper_html: { class: 'col-md-5' }, input_html: {min: 1} %>
      <%= f.input :latlong, label: "Localisation de départ", readonly: true, wrapper_html: { class: 'col-md-3',  'data-toggle' => "tooltip", title: "Cela pour éviter que vous soyez contacté&middot;e&middot;s par des personnes cherchant ce coup de main, qui vivent au-delà de la distance que vous êtes prêt&middot;e&middot;s à parcourir.".html_safe } %>
      <div class="form-group col-md-4">
        <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#mapModal">Ouvrir la carte pour choisir la localisation.</button>
      </div>
    </div>
    <%= f.association :categories, as: :check_boxes, collection: current_organisation.categories, wrapper: :custom_collection_inline %> 
    <%= f.input :autres, hint: "Ce dernier champ sera interprété via <a href=\"https://github.com/AngleMortSociety/doc-markdown/blob/master/md/markdown.md\" target=\"_blank\">Markdown</a>. Vous pouvez mettre des liens, de la mise en forme&hellip;".html_safe, wrapper_html: {'data-toggle' => "tooltip", title: "Ces ajouts ne seront pas utilisables dans la recherche."} %>
  </div>

  <p class="form-text text-muted">
    En publiant cette annonce, vous êtes conscient&middot;e que les informations sont accessibles à tous les membres de l'organisation <%= current_organisation.nom %> ainsi qu'à l'administrateur de ce site. De plus l'accès à l'organisation n'est protégé que par un simple mot de passe.
  </p>
  <div class="form-actions">
    <%= f.button :submit, "Enregistrer l'annonce", class: "btn btn-secondary" %>
  </div>
<% end %>

<!-- Map Modal -->
<div class="modal fade" id="mapModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalLabel">Choix de la localisation</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="map" style='height:500px;' data-map="<%= current_organisation.annonce.latlong %>">
        </div>
      </div>
      <div class="modal-footer">
        <p class="text-muted">Veuillez déplacer le marqueur à la position souhaitée, soit en le glissant, soit par un double-clique. Vous pouvez rechercher un lieu avec la loupe <img src="/packs/media/images/geocoder-a987f06f.png" title="loupe">, puis la touche entrée. Vous pouvez aussi utiliser la cible <img src="/packs/media/images/gps-icon-dfd730fd.svg" height=26 width=26 style="object-fit: cover" title="cible"> pour centrer la carte sur votre position (plutôt sur mobile).<br>
        Le cercle bleu représente la distance que vous avez choisi. Vous pouvez la modifier et revenir voir l'effet.</p>
      </div>
    </div>
  </div>
</div>

app/views/annonces/edit.html.erb
<h1>Modifier l'annonce</h1>

<%= render 'form', annonce: @annonce %>

<p class="mt-2">
<%= link_to 'Annuler', @annonce, class: "btn btn-secondary" %>
<%= link_to 'Retour à la liste', annonces_path, class: "btn btn-outline-secondary" %>
</p>
<% unless @annonce == @annonce.organisation.annonce %>
<p>
<button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#mdpModal">
  Modifier le mot de passe
</button>
<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#supprModal">
  Supprimer l'annonce
</button>
</p>
<% end %>

<!-- Modal -->
<div class="modal fade" id="supprModal" tabindex="-1" role="dialog" aria-labelledby="supprModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="supprModalLabel">Supprimer l'annonce</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_tag annonce_path(id: @annonce.id), method: :delete, class: "simple_form" do %>
        <div class="modal-body">
          <div class="form-inputs">
            <%= label_tag :password %>
            <%= password_field_tag 'password', '' %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
          <input class="btn btn-danger" value='Supprimer cette annonce' type='submit' id='submit-form'/>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="modal fade" id="mdpModal" tabindex="-1" role="dialog" aria-labelledby="mdpModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="mdpModalLabel">Changer le mot de pass de l'annonce</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for(@annonce, wrapper: :input_group ) do |f| %>
        <div class="modal-body">
          <div class="form-inputs">
            <%= f.input :old_password, required: true, label: "Mot de passe actuel" %>
            <%= f.input :password, required: true, label: "Nouveau mot de passe" %>
            <%= f.input :password_confirmation, required: true, label: "Confirmation du nouveau mot de passe" %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Annuler</button>
          <input class="btn btn-secondary" value='Changer' type='submit' id='submit-form'/>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/annonces/index.html.erb
<p class="mt-2"><%= link_to 'Proposer un coup de main', new_annonce_path, class: "btn btn-secondary btn-lg" %></p>

<%= simple_form_for :filtre, url: annonces_path, :method => :get, :html => {:class => "form-inline"} do |f| %>
    <%= f.input :categorie, selected: @categorie&.id, include_blank: "Tout" , required: false, collection: [*current_organisation.categories, Categorie.new(id:-1, nom: "Autres...")], label: "Chercher ", input_html: { class: 'mx-sm-2' } %>
    <% if @categorie&.sur_place %>
	<%= f.hidden_field :latlong,  :value => session["latlong"]%>
	<span data-toggle="tooltip" title="Renseigner votre adresse permettra de filtrer les annonces des personnes qui sont prêtes à venir jusque chez vous." class="mr-sm-2"> 
	<button type="button" class="btn btn-outline-secondary" data-toggle="modal" data-target="#mapModal">Position</button>
	</span>
    <% end %>
    <%= f.button :submit, "Filtrer", class: "btn-secondary" %>
<% end %>

<div class="row row-cols-1 row-cols-md-3 mt-4">
    <% @annonces.shuffle(random: Random.new(Date.today.yday)).each do |annonce| %>
	<div class="col mb-3">
	    <div class="card">
		<div class="card-header"><h5><%= annonce.nom %></h5></div>
		<div class="card-body">
		    <p class="card-text">
		    <% annonce.categories.sample(3).each do |cat| %>
			<%= cat.name.truncate(44, separator: /\.,\s/, omission: '&hellip;').html_safe %><br />
		    <% end %>
		    <% if annonce.categories.length > 3 %>
			&hellip;
		    <% end %>
		    </p>
		</div>
		<div class="card-footer">
		    <small class="text-muted"><%= link_to "Voir toute l'annonce".html_safe, annonce %></small>
		</div>
	    </div>
	</div>
    <% end %>
</div>

<% if @categorie&.sur_place %>
    <!-- Map Modal -->
    <div class="modal fade" id="mapModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
	    <div class="modal-content">
		<div class="modal-header">
		    <h5 class="modal-title" id="modalLabel">Choix de votre position</h5>
		    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		    </button>
		</div>
		<div class="modal-body">
		    <div id="map" style='height:500px;' data-map="<%= current_organisation.annonce.latlong %>">
		    </div>
		</div>
		<div class="modal-footer">
        <p class="text-muted">Veuillez déplacer le marqueur à la position souhaitée, soit en le glissant, soit par un double-clique. Vous pouvez rechercher un lieu avec la loupe <img src="/packs/media/images/geocoder-a987f06f.png" title="loupe">, puis la touche entrée. Vous pouvez aussi utiliser la cible <img src="/packs/media/images/gps-icon-dfd730fd.svg" height=26 width=26 style="object-fit: cover" title="cible"> pour centrer la carte sur votre position (plutôt sur mobile).<br>
        Le cercle bleu représente la distance que vous avez choisi. Vous pouvez la modifier et revenir voir l'effet.</p>
		</div>
	    </div>
	</div>
    </div>
<% end %>

app/views/annonces/new.html.erb
<h1>Nouvelle Annonce</h1>

<%= render 'form', annonce: @annonce %>

<p>
<%= link_to 'Retour à la liste', annonces_path, class: "btn btn-outline-secondary mt-1" %>
</p>

app/views/annonces/show.html.erb
<%= render @annonce %>

<p>
<%= link_to 'Modifier', edit_annonce_path(@annonce), class: "btn btn-outline-secondary" %>
<%= link_to 'Retour à la liste', annonces_path, class: "btn btn-outline-secondary" %>
</p>