config/routes.rb
Rails.application.routes.draw do
  resources :visites, only: :index
  resources :categories
  resources :annonces
  resources :organisations do
    get 'login', on: :member, action: :login_in
    get 'login', on: :collection, action: :login_form
    post 'login', on: :collection
  end
  root to: 'organisations#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_categorie, only: [:show, :edit, :update, :destroy]
  before_action :check_admin
  before_action :check_organisations, only: [:edit, :update, :destroy]
  before_action :check_annonces, only: [:destroy]
  before_action :keep_first_categorie, only: [:edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Categorie.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @categorie = Categorie.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @categorie = Categorie.new(categorie_params)

    respond_to do |format|
      if @categorie.save
        current_organisation&.categories << @categorie
        format.html { redirect_to @categorie, notice: 'Categorie créée avec succès.' }
        format.json { render :show, status: :created, location: @categorie }
      else
        format.html { render :new }
        format.json { render json: @categorie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @categorie.update(categorie_params)
        format.html { redirect_to @categorie, notice: 'Categorie modifiée avec succès.' }
        format.json { render :show, status: :ok, location: @categorie }
      else
        format.html { render :edit }
        format.json { render json: @categorie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @categorie.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Categorie supprimée avec succès.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def check_admin
      unless current_admin
        redirect_to :root, alert: "Accès réservé."
      end
    end
    # before_action :check_organisations, only: [:edit, :update, :destroy]
    def check_organisations
      unless (@categorie.organisations.count == 0) || ((@categorie.organisations.count == 1) && (@categorie.organisations.first == current_organisation))
        redirect_to Categorie, alert: "Cette catégorie est utilisée par d'autres organisations que la votre, cette opération n'est pas permise."
      end
    end
    # before_action :check_annonces, only: [:destroy]
    def check_annonces
      unless (@categorie.annonces.count == 0)
        redirect_to Categorie, alert: "Cette catégorie est utilisée par des annonces, vous ne pouvez pas la supprimer."
      end
    end
    def keep_first_categorie
      if params[:id] == "1"
        redirect_to Categorie, alert: "Cette catégorie ne peut être modifiée."
      end
    end
    def set_categorie
      @categorie = Categorie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def categorie_params
      params.require(:categorie).permit(:nom, :sur_place)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@categorie) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :nom %>
    <%= f.input :sur_place, hint: "C'est à dire que l'on ne peut pas faire à distance, par téléphone ou Internet." %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Modification de Catégorie</h1>

<%= render 'form', categorie: @categorie %>
<p></p>
<p>Attention ! La modification ou la suppression de cette catégorie sera effective pour toutes les organisations qui l'utilisent (<%= @categorie.organisations.count %>). 
Cela apparaîtra sur toutes les annonces qui ont activé cette catégorie (<%= @categorie.annonces.count %>). 
Il vaut souvent mieux créer une nouvelle catégorie, et l'ajouter à votre organisation.</p>
<p>
<% if (@categorie.annonces.count == 0) %>
  <%= link_to 'Supprimer', @categorie, method: :delete, data: { confirm: 'Êtes-vous sûr&middot;e ?'.html_safe }, class: "btn btn-danger" %>
<% end %>
<%= link_to 'Annuler', @categorie, class: "btn btn-outline-secondary" %>
</p>

app/views/categories/index.html.erb
<h1>Catégories</h1>

<p>
<%= link_to 'Nouvelle Catégorie', new_categorie_path, class: "btn btn-secondary" %>
</p>

<ul>
  <% @categories.each do |categorie| %>
    <li><%= link_to categorie.name, categorie %></li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<h1>Nouvelle Catégorie</h1>

<%= render 'form', categorie: @categorie %>

<%= link_to 'Annuler', categories_path, class: "btn btn-secondary" %>

app/views/categories/show.html.erb
<p>
<%= @categorie.nom %><br>
  <%= @categorie.sur_place ? "Sur place" : "À distance" %>
</p>

<p>
<% if (@categorie.organisations.count == 0) || ((@categorie.organisations.count == 1) && (@categorie.organisations.first == current_organisation)) %>
  <%= link_to 'Modifier', edit_categorie_path(@categorie), class: "btn btn-secondary" %>
<% else %>
  <span class="text-muted">Impossible de modifier ou supprimer une catégorie utilisée par d'autres organisations que la votre, mais vous pouvez la retirer de votre organisation.</span><br>
<% end %>
<%= link_to 'Retour à la liste', categories_path, class: "btn btn-outline-secondary" %>
</p>