config/routes.rb
Rails.application.routes.draw do
  resources :visites, only: :index
  resources :categories
  resources :annonces
  resources :organisations do
    get 'login', on: :member, action: :login_in
    get 'login', on: :collection, action: :login_form
    post 'login', on: :collection
  end
  root to: 'organisations#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_messages.html.erb
<%# https://stackoverflow.com/a/17932167 %>
<%# Rails flash messages styled for Bootstrap 3.0 %>
<%# works with Rails 4.0 or Rails 4.1 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coup2Main</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body  lang="fr">
    <!-- Begin Bootstrap Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="/">Coup2Main</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
	<ul class="navbar-nav mr-auto">
	  <% if current_organisation %>
	    <li class="nav-item <%= @organisation == current_organisation ? "active": "" %>">
	      <%= link_to current_organisation, class: 'nav-link' do %>
		<%= current_organisation.nom %>
		<% if current_admin %>
		  (admin)
		<% end %>
	      <% end %>
	    </li>
	  <% end %>
	  <li class="nav-item<%= controller_name == "annonces" ? " active": "" %><%= current_organisation ? "" : " disabled" %>">
	    <a class="nav-link" href="/annonces/">Annonces</a>
	  </li>
	  <% if current_admin %>
	    <li class="nav-item<%= controller_name == "categories" ? " active": "" %>">
	      <a class="nav-link" href="/categories/">Categories</a>
	    </li>
	    <li class="nav-item<%= controller_name == "visites" ? " active": "" %>">
	      <a class="nav-link" href="/visites/">Visites</a>
	    </li>
	  <% end %>
	  <li class="nav-item">
	    <button type="button" class="btn nav-link" data-toggle="modal" data-target="#aideModal">
	      Aide
	    </button>
	  </li>
	</ul>
      </div>
    </nav>
    <!-- End Bootstrap Navbar -->

    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <div class="modal fade" id="aideModal" tabindex="-1" role="dialog" aria-labelledby="aideModalTitle" aria-hidden="true">
      <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
	<div class="modal-content">
	  <div class="modal-header">
	    <h5 class="modal-title" id="aideModalTitle">Aide</h5>
	    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	      <span aria-hidden="true">&times;</span>
	    </button>
	  </div>
	  <div class="modal-body">
	    <% if current_admin %>
	      <p> Lien à partager aux utilisateurs&nbsp;: <code><%= login_organisation_url(current_organisation) %></code></p>
	    <% end %>
	    <p>
	    Vous pouvez proposer des coups de main, dans ce cas cliquez sur <q>Proposer un coup de main</q>, dans la rubrique <%= link_to "Annonces", Annonce %>.
	    </p>
	    <p>
	    Vous pouvez aussi chercher un coup de main et chercher dans les différentes catégories. Pour les catégories <q>sur place</q> vous pourrez préciser votre position géographique, pour vous mettre en lien avec des personnes qui acceptent de se déplacer jusque chez vous.
	    </p>
	    <dl class="row">
	      <dt class="col-sm-3">À distance</dt>
	      <dd class="col-sm-9">il est possible de donner ce coup de main de chez soi, sans se déplacer.</dd>
	      <dt class="col-sm-3">Sur place</dt>
	      <dd class="col-sm-9">il faut se rendre chez la personne pour donner un coup de main.</dd>
	    </dl>
	    <p>
	    Précision : il n’est pas nécessaire de créer plusieurs annonces. Vos coups de main ont changé ? Modifiez votre annonce plutôt que d’en créer une nouvelle. Pour cela, il faut retourner sur votre annonce et cliquer sur <q>modifier</q>. Le mot de passe vous sera demandé.
	    </p>
	    <% if current_organisation %>
	      <p>Si vous avez un soucis avec la plate-forme, vous pouvez chercher une annonce dans la catégorie <%= link_to "Assistance aux utilisateurs de coup2main", controller: "annonces", filtre: {categorie: 1}  %> ou vous référer à <%= link_to "votre organisation", current_organisation %>.</p>
	  <% end %>
	    <p>Le <a href="https://gitlab.com/hamlet/coup2main" target="_blank">code source</a> de cette application est ouvert. Pour proposer des améliorations ou signaler un problème, merci de <a href="https://gitlab.com/hamlet/coup2main/-/issues" target="_blank">créer un ticket</a>.</p>
	  </div>
	</div>
      </div>
    </div>
  </body>
</html>